### ISSUE TITLE
Relicense to MIT / Apache 2

### ISSUE THREAD

**Issue by frewsxcv** [georust/transitfeed#17]
Most (all?) of the other GeoRust projects are dual-licensed as MIT and Apache v2. @bfrog and @medwards are you okay relicensing this project from MIT to MIT/Apache2? Not a big deal, but the consistency across GeoRust projects would be nice!

**Comment by medwards** [comment]
If @bfrog is fine with it, I'm fine with it. I have a bunch of lawer-y questions about what this means precisely because I work in corporate environments with increasingly license oversight, can you direct me to some resources or people I can bug?

**Comment by frewsxcv** [comment]
Hmm what kind of questions do you have? I'm not a lawyer, but depending on the kind of question I can maybe supply some more info

**Comment by medwards** [comment]
Hey, thanks for getting back to me, sorry about the delay:
I was curious about how this works if there are a chain of dependencies, but I think this is largely moot because Apache2/MIT are pretty interchange-able (assuming we're using MIT with a patent grant). The TLDR was whether you pick the license of your dependency if it is dual licensed, and if so, do you then lock anyone who makes you their dependency into that specific license?

**Comment by bfrog** [comment]
I'm fine with this

**Comment by frewsxcv** [comment]
> ...do you then lock anyone who makes you their dependency into that specific license?

Apache and MIT are permissive (not copyleft licenses), so users of the `transitfeed` crate are not locked into using either of these licenses. Or are you wondering something else?
